
public enum Position {
GO, OLD_KENT_ROAD, CMMUNITY_CEST, WHITECHAPEL_RIAD, INCOME_TAX, KINGS_CROSS_STATION, 
THE_ANGEL_ISLINGTON, CHANCE, EUSTON_ROAD, PENTOVILLE_ROAD, IN_JAIL,
PALL_MALL, ELECTRIC_COMPANY, WHITEHALL, NORTHUMRLD_AVENUE, MARYLEBONE_STATION,
BOW_STREET, COMMUNITY_CHEST, MARLBOROUGH_STREET, VINE_STREET, FREE_PARKING,
TRAND, CHANCE2, FLEET_STREET, TRAFALGER_SQUARE, FENCHURCH_STATION, LEICESTER_SQUARE, COVENTRY_STREET,
WATER_WORKS, PICCADILLY, GO_TO_JAIL, REGENT_STREET, OXFORD_STREET, COMMUNITY_CHEST2, BOND_STREET, LIVERPOOL_STATION,
CHANCE3, PARK_LANE, SUPER_TAX, MAYFAIR;

}
